name: Build and Package
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:          
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
      - name: test env vars
        run: |
          echo $GITHUB_ACTOR
        env: 
          GITHUB_ACTOR: ${{ vars.NEW_ACTOR }}
          
        
  
