name: Build and Package
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:          
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
      - name: override default env vars
        run: |
          echo "GITHUB_ACTOR=${{ vars.NEW_ACTOR }}" >> $GITHUB_ENV
      - name: test override vars
        run: |
          echo "expect elizabeth-as-env-variable"
          echo $GITHUB_ACTOR
        env:
          GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
      - name: test env vars
        run: | 
          echo "expect ElizabethBarrord"
          echo $GITHUB_ACTOR
        env: 
          GITHUB_ACTOR: shouldnt-override
          
        
  
